# Generated by Django 6.1.1 on 2026-09-29 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="The id sent to the proxy.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("value", "Value"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        default="value",
                        max_length=20,
                    ),
                ),
                (
                    "input_price_micros",
                    models.PositiveBigIntegerField(
                        help_text="Provider cost in micro-dollars per 1M input tokens (1,000,000 = $1)."
                    ),
                ),
                (
                    "output_price_micros",
                    models.PositiveBigIntegerField(
                        help_text="Provider cost in micro-dollars per 1M output tokens (1,000,000 = $1)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "AI model",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "markup_percent",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Added on top of provider cost. 50 = cost x 1.5.",
                    ),
                ),
                (
                    "signup_grant_micros",
                    models.PositiveBigIntegerField(
                        default=2000000,
                        help_text="Free credit for each new user, in micro-dollars.",
                    ),
                ),
            ],
            options={
                "verbose_name": "pricing settings",
                "verbose_name_plural": "pricing settings",
            },
        ),
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_micros",
                    models.BigIntegerField(
                        help_text="Positive adds credit, negative removes it."
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("grant", "Signup grant"),
                            ("topup", "Top-up"),
                            ("charge", "Charge"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="billing.billingaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ledger entries",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
