# Generated by Django 6.1.1 on 2026-09-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="include_memories",
            field=models.BooleanField(default=True),
        ),
    ]
