# Generated by Django 6.1.1 on 2026-09-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="global_system_prompt",
            field=models.TextField(
                blank=True,
                help_text="Instruction added to every chat session.",
                max_length=4000,
            ),
        ),
    ]
